openapi: 3.0.0
OntologyTerm:
  required:
    - accession
    - name
  properties:
    accession:
      type: string
    name:
      type: string
    value:
      type: string
    cvLabel:
      type: string