openapi: 3.0.0
 Contact:
   requires:
     - contactType
   properties:
     contactType:
       enum: [Submitter, LabHead]
       type: string
     attributes:
       type: array
       xml:
         name: attribute
         wrapped: true
       items:
        $ref: "../common/OntologyTerm.yaml"


