openapi: 3.0.0
 Dataset:
   requires:
     - "accession"
     - "title"
     - "summary"
     - "organisms"
     - "instruments"
     - "modifications"
     - "contacts"
     - "dataFiles"
     - "fullDatasetLink"
   properties:
     accession:
       type: "string"
     title:
      type: "string"
     summary:
      type: "string"
     organisms:
      type: "array"
      xml:
        name: "organism"
      items:
        $ref: "../common/OntologyTerm.yaml"
    instruments:
      type: "array"
      xml:
        name: "instrument"
        wrapped: true
      items:
        $ref: "../common/OntologyTerm.yaml"
    modifications:
      type: "array"
      xml:
        name: "modification"
        wrapped: true
      items:
        $ref: "../common/OntologyTerm.yaml"
    contacts:
      type: "array"
      xml:
        name: "contact"
        wrapped: true
      items:
        $ref: "contact.yaml"
    publications:
      type: "array"
      xml:
        name: "publication"
        wrapped: true
      items:
        $ref: "../common/OntologyTerm.yaml"
    keywords:
      type: "array"
      xml:
        name: "keyword"
        wrapped: true
      items:
        $ref: "../common/OntologyTerm.yaml"
    fullDatasetLink:
      type: "object"
      $ref: "../common/OntologyTerm.yaml"
    dataFiles:
      type: "array"
      xml:
        name: "dataFile"
        wrapped: true
      items:
        $ref: "../common/OntologyTerm.yaml"



